/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package faceverificationgui;

import javax.swing.JFileChooser;

/**
 *
 * @author bsidb
 */
public class ClassifierTestingForm extends javax.swing.JFrame {

    /**
     * Creates new form ClassifierTestingForm
     */
    public ClassifierTestingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPosFile = new javax.swing.JTextField();
        jButtonPosFile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNegFile = new javax.swing.JTextField();
        jButtonNegFile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldModelFile = new javax.swing.JTextField();
        jButtonModel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxProgram = new javax.swing.JComboBox();
        jButtonProgram = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldResult = new javax.swing.JTextField();
        jButtonResult = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCL = new javax.swing.JTextArea();
        jButtonGenCL = new javax.swing.JButton();
        jButtonRunCL = new javax.swing.JButton();
        jButtonRun = new javax.swing.JButton();
        jLabelState = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sans Serif", 3, 36)); // NOI18N
        jLabel1.setText("Classifier Testing");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("I/O"));

        jLabel2.setText("Positive Sample File");

        jButtonPosFile.setText("Select");
        jButtonPosFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosFileActionPerformed(evt);
            }
        });

        jLabel3.setText("Negative Sample File");

        jButtonNegFile.setText("Select");
        jButtonNegFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegFileActionPerformed(evt);
            }
        });

        jLabel4.setText("Model File");

        jButtonModel.setText("Select");
        jButtonModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModelActionPerformed(evt);
            }
        });

        jLabel6.setText("Program");

        jComboBoxProgram.setEditable(true);
        jComboBoxProgram.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "adaboost_test_wrap.exe", " " }));

        jButtonProgram.setText("Select");
        jButtonProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProgramActionPerformed(evt);
            }
        });

        jLabel7.setText("Result");

        jButtonResult.setText("Select");
        jButtonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldPosFile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPosFile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jComboBoxProgram, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(jTextFieldModelFile, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNegFile, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNegFile)
                            .addComponent(jButtonModel)
                            .addComponent(jButtonProgram)
                            .addComponent(jButtonResult))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPosFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPosFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNegFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNegFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldModelFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jButtonModel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonProgram))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonResult)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Advanced"));

        jLabel5.setText("Command Line");

        jTextAreaCL.setColumns(20);
        jTextAreaCL.setLineWrap(true);
        jTextAreaCL.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCL);

        jButtonGenCL.setText("Generate");
        jButtonGenCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenCLActionPerformed(evt);
            }
        });

        jButtonRunCL.setText("Run");
        jButtonRunCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGenCL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRunCL)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenCL)
                    .addComponent(jButtonRunCL)))
        );

        jButtonRun.setText("Run");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        jLabelState.setFont(new java.awt.Font("Sans Serif", 2, 14)); // NOI18N
        jLabelState.setText("Welcome!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonRun)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRun)
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRunCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCLActionPerformed
        // TODO add your handling code here:
        new RunningCLThread(jTextAreaCL.getText(), jLabelState).start();
    }//GEN-LAST:event_jButtonRunCLActionPerformed

    private void jButtonPosFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosFileActionPerformed
        // TODO add your handling code here:
        new TJchooser(jTextFieldPosFile).openFile(".", JFileChooser.FILES_ONLY, false);
    }//GEN-LAST:event_jButtonPosFileActionPerformed

    private void jButtonNegFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegFileActionPerformed
        // TODO add your handling code here:
        new TJchooser(jTextFieldNegFile).openFile(".", JFileChooser.FILES_ONLY, false);
    }//GEN-LAST:event_jButtonNegFileActionPerformed

    private void jButtonModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModelActionPerformed
        // TODO add your handling code here:
        new TJchooser(jTextFieldModelFile).openFile(".", JFileChooser.FILES_ONLY, false);
    }//GEN-LAST:event_jButtonModelActionPerformed

    private void jButtonProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProgramActionPerformed
        // TODO add your handling code here:
        jComboBoxProgram.setSelectedItem(new TJchooser(null).openFile(".", JFileChooser.FILES_ONLY, false));
    }//GEN-LAST:event_jButtonProgramActionPerformed

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
        // TODO add your handling code here:
        new RunningCLThread(getCmdFromGUI(), jLabelState).start();
    }//GEN-LAST:event_jButtonRunActionPerformed

    private void jButtonGenCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenCLActionPerformed
        // TODO add your handling code here:
        jTextAreaCL.setText(getCmdFromGUI());
    }//GEN-LAST:event_jButtonGenCLActionPerformed

    private void jButtonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultActionPerformed
        // TODO add your handling code here:
        jComboBoxProgram.setSelectedItem(new TJchooser(jTextFieldResult).openFile(".", JFileChooser.FILES_ONLY, false));
    }//GEN-LAST:event_jButtonResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassifierTestingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassifierTestingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassifierTestingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassifierTestingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassifierTestingForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenCL;
    private javax.swing.JButton jButtonModel;
    private javax.swing.JButton jButtonNegFile;
    private javax.swing.JButton jButtonPosFile;
    private javax.swing.JButton jButtonProgram;
    private javax.swing.JButton jButtonResult;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JButton jButtonRunCL;
    private javax.swing.JComboBox jComboBoxProgram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCL;
    private javax.swing.JTextField jTextFieldModelFile;
    private javax.swing.JTextField jTextFieldNegFile;
    private javax.swing.JTextField jTextFieldPosFile;
    private javax.swing.JTextField jTextFieldResult;
    // End of variables declaration//GEN-END:variables

    CTestConfiguration config = new CTestConfiguration();
    String getCmdFromGUI(){
        config.set(CTestConfiguration.PPos, jTextFieldPosFile.getText());
        config.set(CTestConfiguration.PNeg, jTextFieldNegFile.getText());
        config.set(CTestConfiguration.PModel, jTextFieldModelFile.getText());
        config.set(CTestConfiguration.PProgram,jComboBoxProgram.getSelectedItem().toString());
        config.set(CTestConfiguration.PResult, jTextFieldResult.getText());
        return config.generateCommand();
    }
}

class CTestConfiguration extends GUIConfiguration{
    public static final String PPos="PositiveSample";
    public static final String PNeg="NegativeSample";
    public static final String PResult="Result";
    public static final String PModel="ModelFilename";
    public static final String PProgram="Program";
    
    @Override
    public String generateCommand(){
        String cmd;
        try{
            cmd = config.getProperty(PProgram)
                    + " " + config.getProperty(PModel)
                    + " " + config.getProperty(PPos)
                    + " " + config.getProperty(PNeg)
                    + " " + config.getProperty(PResult);
                    
        }catch(Exception e){
            cmd = e.toString();
        }
        return cmd;
    }
}