<%-- 
    Document   : database
    Created on : 2013-3-18, 9:57:54
    Author     : bsidb
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page import="javax.swing.ImageIcon"%>
<%@page import="java.awt.Image"%>
<%@page import="java.io.FilenameFilter"%>
<%@page import="java.io.File"%>
<!DOCTYPE html>

<html>
	<head>
		<title>RunJS</title>
		<script class="jquery library" src="http://sandbox.runjs.cn/js/sandbox/jquery/jquery-1.8.2.min.js" type="text/javascript"></script>    <script class="jquery library" src="https://raw.github.com/GBKS/Wookmark-jQuery/master/jquery.wookmark.min.js" type="text/javascript"></script>
                <style>
/**
 * Grid container
 */
#tiles {
list-style-type: none;
position: relative; /** Needed to ensure items are laid out relative to this container **/
margin: 0;
}

/**
 * Grid items
 */
#tiles li {
width: 200px;
background-color: #ffffff;
border: 1px solid #00ff00;
-moz-border-radius: 2px;
-webkit-border-radius: 2px;
border-radius: 2px;
/** display: none; /** Hide items initially to avoid a flicker effect **/
  cursor: pointer;
padding: 4px;
}

#tiles li img {
display: block;
}

/**
 * Grid item text
 */
#tiles li p {
color: #666;
font-size: 12px;
margin: 7px 0 0 7px;
}

/**
 * Some extra styles to randomize heights of grid items.
 */
#tiles ali:nth-child(3n) {
height: 175px;
}

#tiles ali:nth-child(4n-3) {
padding-bottom: 30px;
}

#tiles ali:nth-child(5n) {
height: 250px;
}

/** General page styling **/
  
html {
background-color: #e9e9e9;
}

#main {
padding: 30px 10px 30px 10px;
}

header h1 {
text-align: center;
font-size: 24px;
font-weight: normal;
margin: 30px 0 3px 0;
}

header p {
text-align: center;
font-size: 13px;
color: #777;
margin: 0;
}
        </style>
	    		<script>
// Prepare layout options.
var options = {
  autoResize: true, // This will auto-update the layout when the browser window is resized.
  container: $('#example'), // Optional, used for some extra CSS styling
  offset: 5, // Optional, the distance between grid items
  itemWidth: 100 // Optional, the width of a grid item
};

handler = $('#tiles li');
handler.wookmark(options);
            
                </script>
        
	</head>
	<body>
    <h2>A live example</h2> 
    <p>Hello</p>
    <!-- Following is Java Server Page --> 
    <div id="example"> <ul id="tiles">
    <%
    	java.io.File currentFolderFile = new java.io.File("/home/bsidb/Yunio/document_laptop/work/face/FG-NET1/");
        System.out.println(currentFolderFile.getAbsolutePath());
        File[] files = currentFolderFile.listFiles(new FilenameFilter() {

            @Override
            public boolean accept(File file, String string) {
                return string.matches(".+[(jpg|png|gif|JPG)]");
            }
        });
        for(File f:files){
            ImageIcon imageIcon = new ImageIcon(f.getCanonicalPath());
            out.println("<li style=\"height: " +105 + 
                    "px;width: " + 105
                    +"px;\"><img src=\"/FRWeb/FG-NET1/" + f.getName() + "\" + style=\"height:100px;width:100px;\"></img></li>");
        }
    %>
       </ul>
    </div>
	</body>
</html>
    	
	
<!-- Generated by RunJS (Sat Mar 16 09:49:52 CST 2013) 1ms -->
